markdown: kramdown
redcarpet:
  extensions: [
      "no_intra_emphasis",
      "fenced_code_blocks",
      "autolink",
      "strikethrough",
      "superscript",
      "tables",
      "lax_spacing",
      "space_after_headers
      ",
      "quote",
      "footnotes",
    ]
